apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    receivers:
    - name: 'notifications'
      email_configs:
      - to: chris.dolan@gmail.com 
        from: chris.dolan@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: chris.dolan@gmail.com
        auth_identity: chris.dolan@gmail.com
        auth_password: ${GM_APP_PASSWORD}
        send_resolved: true
        headers:
          subject: "Prometheus - Alert"
          text: "{{ range .Alerts }} Hi,\n{{ .Annotations.summary }}\n{{ .Annotations.description }} {{end}}"

      slack_configs:
      - channel: '#upcommerce-devs' 
        send_resolved: true
        api_url: ${UPCOMMERCE_SLACK_API_URL} 
  
    route:
      group_wait: 10s
      group_interval: 2m
      routes:
        - match:
            receiver: 'email-notifications'
          continue: true
        - match:
            receiver: 'slack-notifications'
          continue: true
      repeat_interval: 2m
